using System.Text.Json.Serialization;

namespace CampaignVault.Models;

/// <summary>
/// Per-campaign configuration document.
/// 
/// Document ID is now generated by <see cref="Data.CampaignDocumentKeys.Config"/> (e.g. "campaigns/{name}/config").
/// This replaces the old implicit singleton "campaign/config" pattern.
/// 
/// Controls the (locked) ruleset system for the campaign + any house-rule overrides.
/// Loaded by RulesetActionHandler on every ruleset action dispatch.
/// </summary>
public class CampaignConfig
{
    /// <summary>
    /// Document ID. Should be set via CampaignDocumentKeys.Config(campaignName) rather than hardcoded.
    /// Kept mutable for Raven load/store compatibility.
    /// </summary>
    public string Id { get; set; } = default!;

    /// <summary>
    /// The active TTRPG ruleset for this campaign.
    /// Determines which IRulesetResolver handles RulesetAction WorldChanges.
    /// 
    /// This value is locked at the Campaign level once the campaign is initialized
    /// (see first-class Campaign model + InitializeCampaign tool).
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public RulesetSystem ActiveSystem { get; set; } = RulesetSystem.Dnd5e;

    /// <summary>
    /// Optional house-rule overrides passed to resolvers.
    /// Keys and values are resolver-specific. Examples:
    /// "lingeringInjuries" → "true" (D&amp;D 5e optional rule)
    /// "mapEnabled" → "true" (PF2e multi-attack penalty tracking)
    /// </summary>
    public Dictionary<string, string> SystemOptions { get; set; } = [];

    /// <summary>
    /// Maximum number of pressure nags to surface in a single tool response.
    /// Defaults to 5.
    /// </summary>
    public int MaxPressuresPerResponse { get; set; } = 5;
}
