using System.Text.Json.Serialization;
using CampaignVault.Data.Templates;

namespace CampaignVault.Models;

/// <summary>
/// Per-campaign configuration document.
/// 
/// Document ID is now generated by <see cref="Data.CampaignDocumentKeys.Config"/> (e.g. "campaigns/{name}/config").
/// This replaces the old implicit singleton "campaign/config" pattern.
/// 
/// Controls the (locked) ruleset system for the campaign + any house-rule overrides.
/// Loaded by RulesetActionHandler on every ruleset action dispatch.
/// </summary>
public class CampaignConfig
{
    /// <summary>
    /// Document ID. Should be set via CampaignDocumentKeys.Config(campaignName) rather than hardcoded.
    /// Kept mutable for Raven load/store compatibility.
    /// </summary>
    public string Id { get; set; } = null!;

    /// <summary>
    /// The active TTRPG ruleset for this campaign.
    /// Determines which IRulesetResolver handles RulesetAction WorldChanges.
    /// 
    /// This value is locked at the Campaign level once the campaign is initialized
    /// (see first-class Campaign model + InitializeCampaign tool).
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public RulesetSystem ActiveSystem { get; set; } = RulesetSystem.Dnd5e;

    /// <summary>
    /// Optional house-rule overrides passed to resolvers.
    /// Keys and values are resolver-specific. Examples:
    /// "lingeringInjuries" → "true" (D&amp;D 5e optional rule)
    /// "mapEnabled" → "true" (PF2e multi-attack penalty tracking)
    /// </summary>
    public Dictionary<string, string> SystemOptions { get; set; } = [];

    /// <summary>
    /// Maximum number of pressure nags to surface in a single tool response.
    /// Defaults to 5.
    /// </summary>
    public int MaxPressuresPerResponse { get; set; } = 5;

    /// <summary>
    /// The number of in-game days a pressure nag is suppressed after being surfaced.
    /// Defaults to 1 (meaning it stays hidden for 1 day, then reappears if ignored).
    /// </summary>
    public int PressureCooldownDays { get; set; } = 1;

    /// <summary>
    /// The number of times a pressure nag is suppressed before escalating to ENGINE WARNING.
    /// Defaults to 3.
    /// </summary>
    public int PressureEscalationCount { get; set; } = 3;

    /// <summary>
    /// The number of in-game days before a Trivial memory drifts or decays.
    /// Defaults to 20.
    /// </summary>
    public int MemoryTrivialDecayDays { get; set; } = 20;

    /// <summary>
    /// The number of in-game days before an Important memory drifts or decays.
    /// Defaults to 40.
    /// </summary>
    public int MemoryImportantDecayDays { get; set; } = 40;

    /// <summary>
    /// The number of in-game days before economic demand drifts or decays.
    /// Defaults to 7.
    /// </summary>
    public int EconomicDemandDecayDays { get; set; } = 7;

    /// <summary>
    /// Base per-day need accumulation rate during simulation (multiplied by days passed).
    /// Defaults to 10.
    /// </summary>
    public float NeedAccumulationRate { get; set; } = 10f;

    /// <summary>
    /// Baseline need level that scheduled activities settle NPCs toward.
    /// Routines matching "eat" keywords settle hunger to this value; "sleep" settles tiredness, etc.
    /// Defaults to 20.
    /// </summary>
    public int? NeedSatisfactionBaseline { get; set; } = 20;

    /// <summary>
    /// Multiplier applied to thirst need accumulation.
    /// Defaults to 1.2.
    /// </summary>
    public float ThirstAccumulationMultiplier { get; set; } = 1.2f;

    /// <summary>
    /// Multiplier applied to tiredness need accumulation.
    /// Defaults to 0.8.
    /// </summary>
    public float TirednessAccumulationMultiplier { get; set; } = 0.8f;

    /// <summary>
    /// Per-day morale drift when NPCs are in sustained bad need states.
    /// Defaults to -0.8.
    /// </summary>
    public float MoraleDriftPerDay { get; set; } = -0.8f;

    /// <summary>
    /// Grace period (in days) before transient NPCs are evicted from unvisited locations.
    /// Defaults to 1.
    /// </summary>
    public int TransientEvictionGraceDays { get; set; } = 1;

    /// <summary>
    /// Number of commits with no recorded time passage (no day-boundary crossing, no MinutesElapsed
    /// on any change) before TimeStalenessPressureContributor nudges the DM-LLM to record narrative
    /// time passage. Defaults to 15.
    /// </summary>
    public int TimeStalenessNudgeThreshold { get; set; } = 15;

    /// <summary>
    /// Days a rumor must age without resolution before surfacing world pressure.
    /// Defaults to 5.
    /// </summary>
    public int RumorAgingPressureDays { get; set; } = 5;

    /// <summary>
    /// Days a forgotten rumor must age before being archived (deleted) from the campaign.
    /// Defaults to 30.
    /// </summary>
    public int RumorArchiveAfterDays { get; set; } = 30;

    /// <summary>
    /// Days without quest progress before staleness pressure is surfaced.
    /// Defaults to 10.
    /// </summary>
    public int QuestStalenessDays { get; set; } = 10;

    /// <summary>
    /// Days a plot thread can sit at Climax before auto-resolving with a disaster outcome.
    /// Defaults to 10.
    /// </summary>
    public int PlotThreadClimaxAutoResolveDays { get; set; } = 10;

    /// <summary>
    /// HP ratio threshold (current/max) below which a character is considered critically wounded.
    /// Defaults to 0.25.
    /// </summary>
    public float CharacterPressureHpCriticalThreshold { get; set; } = 0.25f;

    public float TensionWeightNeed { get; set; } = 0.30f;
    public float TensionWeightMemory { get; set; } = 0.25f;
    public float TensionWeightRelational { get; set; } = 0.25f;
    public float TensionWeightDisposition { get; set; } = 0.20f;

    public float TensionValencePositive { get; set; } = 0.3f;
    public float TensionValenceNeutral { get; set; } = 0.5f;
    public float TensionValenceNegative { get; set; } = 0.8f;
    public float TensionValenceTraumatic { get; set; } = 1.0f;

    public float NeedConflictThreshold { get; set; } = 70f;
    public float NeedConflictTensionBoost { get; set; } = 15f;

    public int DispositionMinTokenLength { get; set; } = 3;
    public Dictionary<string, List<string>> DispositionKeywordExpansions { get; set; } = [];

    public List<string> GratitudeHeuristicTokens { get; set; } =
    [
        "gift", "gave", "granted", "necklace", "reward", "favor", "saved", "rescued"
    ];

    public int InitiativeSuppressionRetentionDays { get; set; } = 30;

    /// <summary>
    /// BehavioralTension (0-100 scale) threshold above which an NPC's top initiative candidate (if
    /// Urgency is at least High) produces an advisory TurnIntentSignal suggesting the NPC should
    /// act/speak next. Defaults to 60. Never a hard gate — the player can always act regardless.
    /// </summary>
    public double BehavioralTensionSpeakingThreshold { get; set; } = 60;

    /// <summary>
    /// Days after a persistent relationship initiative was surfaced before sim may re-arm it
    /// (affection, resentment, trust bands only).
    /// </summary>
    public int RelationalRearmIntervalDays { get; set; } = 7;

    /// <summary>
    /// Days since a party companion's last recorded Conversation event (while a PC is present in the
    /// scene) before ConversationStalenessInitiativeProvider surfaces a "hasn't spoken up in a while"
    /// candidate. Only fires when a prior Conversation event exists at all — a companion with no
    /// conversation history yet (e.g. freshly introduced) doesn't fire on day one.
    /// </summary>
    public int ConversationStalenessDaysThreshold { get; set; } = 2;

    /// <summary>
    /// Per-campaign resource pool definitions (spell slots, focus points, action points, etc.).
    /// If empty, built-in defaults are loaded based on ActiveSystem.
    /// Allows homebrew variants and custom systems.
    /// Key = pool name (e.g., "spell_slots_1", "focus_points").
    /// </summary>
    public Dictionary<string, ResourcePoolTemplate> ResourcePoolSchemas { get; set; } = [];

    /// <summary>
    /// When true, relationship modifiers on social skill checks use the reverse relationship as a fallback
    /// if the target has no recorded opinion of the actor (reads half of actor → target relationship, rounded down).
    /// Defaults to false — only target → actor relationships directly modify rolls.
    /// </summary>
    public bool SymmetricRelationshipFallback { get; set; } = false;

    /// <summary>
    /// When true, the engine automatically repairs one-way location exits by appending reverse exits
    /// when they are missing (unless the forward exit is marked OneWay: true).
    /// Defaults to false — many campaigns use intentional one-way exits (chutes, secret doors, traps).
    /// </summary>
    public bool AutoRepairLocationConnectivity { get; set; } = false;

    /// <summary>
    /// Number of events surfaced in ambient "story so far" context (get_world_state, get_scene).
    /// Selected by importance (Core/Important survive first), then recency. Defaults to 5.
    /// </summary>
    public int EventContextBudgetAmbient { get; set; } = 5;

    /// <summary>
    /// Number of events surfaced in get_npc_context. Defaults to 10.
    /// </summary>
    public int EventContextBudgetNpc { get; set; } = 10;

    /// <summary>
    /// Default number of events returned by recall_history when the caller doesn't override via `limit`.
    /// Defaults to 5.
    /// </summary>
    public int EventContextBudgetRecall { get; set; } = 5;
}

/// <summary>
/// Template for initializing a resource pool on character creation.
/// Used by character_create handler to populate Character.SystemExtension.ResourcePools.
/// Can be defined inline in CampaignConfig.ResourcePoolSchemas or loaded from YAML via ResourcePoolProvider.
/// </summary>
public record ResourcePoolTemplate : RulesetTemplate
{
    /// <summary>When this pool recovers. Null means "not set" — inherited from a parent template via YAML.</summary>
    [JsonPropertyName("recovery")]
    public RecoveryType? Recovery { get; set; }

    /// <summary>Base maximum value (can be overridden per-character based on level/class). Null = inherit from parent.</summary>
    [JsonPropertyName("defaultMax")]
    public int? DefaultMax { get; set; }

    /// <summary>TTRPG systems this pool applies to ("dnd5e", "pf2e", "fallout2d20"). Null = all systems.</summary>
    [JsonPropertyName("applicableSystems")]
    public List<string>? ApplicableSystems { get; set; }

    /// <summary>
    /// Classes that receive this pool (substring match on class name, e.g. "monk", "battle master").
    /// Null = not class-gated (spell slot pools use caster-level rules instead).
    /// </summary>
    [JsonPropertyName("applicableClasses")]
    public List<string>? ApplicableClasses { get; set; }

    /// <summary>For slot-based pools: map character level to max count. E.g., "1" -> 4, "2" -> 3 for spell slots.</summary>
    [JsonPropertyName("levelToMaxMap")]
    public Dictionary<string, int>? LevelToMaxMap { get; set; }

    /// <summary>
    /// When true, pool is only initialized via <see cref="FeatDefinition.ExtraPools"/>, not class/caster rules.
    /// </summary>
    [JsonPropertyName("featGrantedOnly")]
    public bool? FeatGrantedOnly { get; set; }

    /// <summary>
    /// Merge two templates: child fields win; parent fills gaps.
    /// Used by RulesetTemplateResolver during YAML inheritance resolution.
    /// </summary>
    public static ResourcePoolTemplate Merge(ResourcePoolTemplate child, ResourcePoolTemplate parent)
    {
        var merged = child with
        {
            Description = child.Description ?? parent.Description,
            Recovery = child.Recovery ?? parent.Recovery,
            DefaultMax = child.DefaultMax ?? parent.DefaultMax,
            ApplicableSystems = child.ApplicableSystems?.Count > 0
                ? child.ApplicableSystems
                : parent.ApplicableSystems,
            ApplicableClasses = child.ApplicableClasses?.Count > 0
                ? child.ApplicableClasses
                : parent.ApplicableClasses,
            FeatGrantedOnly = child.FeatGrantedOnly ?? parent.FeatGrantedOnly,
        };

        if (parent.LevelToMaxMap?.Count > 0)
        {
            var mergedMap = child.LevelToMaxMap != null
                ? new Dictionary<string, int>(child.LevelToMaxMap)
                : new Dictionary<string, int>();
            foreach (var (k, v) in parent.LevelToMaxMap)
                mergedMap.TryAdd(k, v);
            merged = merged with { LevelToMaxMap = mergedMap };
        }

        return merged;
    }
}
