using System.Text.Json.Serialization;

namespace CampaignVault.Models;

/// <summary>
/// Per-campaign configuration document.
/// 
/// Document ID is now generated by <see cref="Data.CampaignDocumentKeys.Config"/> (e.g. "campaigns/{name}/config").
/// This replaces the old implicit singleton "campaign/config" pattern.
/// 
/// Controls the (locked) ruleset system for the campaign + any house-rule overrides.
/// Loaded by RulesetActionHandler on every ruleset action dispatch.
/// </summary>
public class CampaignConfig
{
    /// <summary>
    /// Document ID. Should be set via CampaignDocumentKeys.Config(campaignName) rather than hardcoded.
    /// Kept mutable for Raven load/store compatibility.
    /// </summary>
    public string Id { get; set; } = default!;

    /// <summary>
    /// The active TTRPG ruleset for this campaign.
    /// Determines which IRulesetResolver handles RulesetAction WorldChanges.
    /// 
    /// This value is locked at the Campaign level once the campaign is initialized
    /// (see first-class Campaign model + InitializeCampaign tool).
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public RulesetSystem ActiveSystem { get; set; } = RulesetSystem.Dnd5e;

    /// <summary>
    /// Optional house-rule overrides passed to resolvers.
    /// Keys and values are resolver-specific. Examples:
    /// "lingeringInjuries" → "true" (D&amp;D 5e optional rule)
    /// "mapEnabled" → "true" (PF2e multi-attack penalty tracking)
    /// </summary>
    public Dictionary<string, string> SystemOptions { get; set; } = [];

    /// <summary>
    /// Maximum number of pressure nags to surface in a single tool response.
    /// Defaults to 5.
    /// </summary>
    public int MaxPressuresPerResponse { get; set; } = 5;

    /// <summary>
    /// The number of in-game days a pressure nag is suppressed after being surfaced.
    /// Defaults to 1 (meaning it stays hidden for 1 day, then reappears if ignored).
    /// </summary>
    public int PressureCooldownDays { get; set; } = 1;

    /// <summary>
    /// The number of times a pressure nag is suppressed before escalating to ENGINE WARNING.
    /// Defaults to 3.
    /// </summary>
    public int PressureEscalationCount { get; set; } = 3;

    /// <summary>
    /// The number of in-game days before a Trivial memory drifts or decays.
    /// Defaults to 20.
    /// </summary>
    public int MemoryTrivialDecayDays { get; set; } = 20;

    /// <summary>
    /// The number of in-game days before an Important memory drifts or decays.
    /// Defaults to 40.
    /// </summary>
    public int MemoryImportantDecayDays { get; set; } = 40;

    /// <summary>
    /// The number of in-game days before economic demand drifts or decays.
    /// Defaults to 7.
    /// </summary>
    public int EconomicDemandDecayDays { get; set; } = 7;

    /// <summary>
    /// Base per-day need accumulation rate during simulation (multiplied by days passed).
    /// Defaults to 10.
    /// </summary>
    public float NeedAccumulationRate { get; set; } = 10f;

    /// <summary>
    /// Multiplier applied to thirst need accumulation.
    /// Defaults to 1.2.
    /// </summary>
    public float ThirstAccumulationMultiplier { get; set; } = 1.2f;

    /// <summary>
    /// Multiplier applied to tiredness need accumulation.
    /// Defaults to 0.8.
    /// </summary>
    public float TirednessAccumulationMultiplier { get; set; } = 0.8f;

    /// <summary>
    /// Per-day morale drift when NPCs are in sustained bad need states.
    /// Defaults to -0.8.
    /// </summary>
    public float MoraleDriftPerDay { get; set; } = -0.8f;

    /// <summary>
    /// Grace period (in days) before transient NPCs are evicted from unvisited locations.
    /// Defaults to 1.
    /// </summary>
    public int TransientEvictionGraceDays { get; set; } = 1;

    /// <summary>
    /// Days a rumor must age without resolution before surfacing world pressure.
    /// Defaults to 5.
    /// </summary>
    public int RumorAgingPressureDays { get; set; } = 5;

    /// <summary>
    /// Days without quest progress before staleness pressure is surfaced.
    /// Defaults to 10.
    /// </summary>
    public int QuestStalenessDays { get; set; } = 10;

    /// <summary>
    /// HP ratio threshold (current/max) below which a character is considered critically wounded.
    /// Defaults to 0.25.
    /// </summary>
    public float CharacterPressureHpCriticalThreshold { get; set; } = 0.25f;

    public float TensionWeightNeed { get; set; } = 0.30f;
    public float TensionWeightMemory { get; set; } = 0.25f;
    public float TensionWeightRelational { get; set; } = 0.25f;
    public float TensionWeightDisposition { get; set; } = 0.20f;

    public float TensionValencePositive { get; set; } = 0.3f;
    public float TensionValenceNeutral { get; set; } = 0.5f;
    public float TensionValenceNegative { get; set; } = 0.8f;
    public float TensionValenceTraumatic { get; set; } = 1.0f;

    public float NeedConflictThreshold { get; set; } = 70f;
    public float NeedConflictTensionBoost { get; set; } = 15f;

    public int DispositionMinTokenLength { get; set; } = 3;
    public Dictionary<string, List<string>> DispositionKeywordExpansions { get; set; } = [];

    public List<string> GratitudeHeuristicTokens { get; set; } =
    [
        "gift", "gave", "granted", "necklace", "reward", "favor", "saved", "rescued"
    ];

    public int InitiativeSuppressionRetentionDays { get; set; } = 30;

    /// <summary>
    /// Days after a persistent relationship initiative was surfaced before sim may re-arm it
    /// (affection, resentment, trust bands only).
    /// </summary>
    public int RelationalRearmIntervalDays { get; set; } = 7;

    /// <summary>
    /// Per-campaign resource pool definitions (spell slots, focus points, action points, etc.).
    /// If empty, built-in defaults are loaded based on ActiveSystem.
    /// Allows homebrew variants and custom systems.
    /// Key = pool name (e.g., "spell_slots_1", "focus_points").
    /// </summary>
    public Dictionary<string, ResourcePoolTemplate> ResourcePoolSchemas { get; set; } = [];
}

/// <summary>
/// Template for initializing a resource pool on character creation.
/// Used by character_create handler to populate Character.SystemExtension.ResourcePools.
/// </summary>
public class ResourcePoolTemplate
{
    /// <summary>Pool identifier (e.g., "spell_slots_1", "sorcerer_points", "focus_points", "action_points").</summary>
    [JsonPropertyName("poolName")]
    public string PoolName { get; set; } = default!;

    /// <summary>When this pool recovers (LongRest, ShortRest, EncounterEnd, Daily, Never).</summary>
    [JsonPropertyName("recovery")]
    public RecoveryType Recovery { get; set; } = RecoveryType.LongRest;

    /// <summary>Base maximum value (can be overridden per-character based on level/class).</summary>
    [JsonPropertyName("defaultMax")]
    public int DefaultMax { get; set; }

    /// <summary>TTRPG systems this pool applies to ("dnd5e", "pf2e", "fallout2d20"). Null = all systems.</summary>
    [JsonPropertyName("applicableSystems")]
    public List<string>? ApplicableSystems { get; set; }

    /// <summary>For slot-based pools: map character level to max count. E.g., "1" -> 4, "2" -> 3 for spell slots.</summary>
    [JsonPropertyName("levelToMaxMap")]
    public Dictionary<string, int>? LevelToMaxMap { get; set; }

    /// <summary>Human-readable description for DM reference.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
}
