namespace CampaignVault.Tools;

public record CommitTypeSchema(
    string Type,
    string Category,
    string Description,
    string[] RequiredFields,
    string[] OptionalFields,
    bool HasSideEffects,
    string[] SideEffects,
    string[] CoCommitHints,
    string? Example = null
);

internal static class CommitSchemaRegistry
{
    private static readonly IReadOnlyList<CommitTypeSchema> All = BuildAll();

    public static IReadOnlyList<CommitTypeSchema> GetAll(string? category = null)
    {
        if (string.IsNullOrWhiteSpace(category)) return All;
        return All.Where(s => s.Category.Equals(category.Trim(), StringComparison.OrdinalIgnoreCase)).ToList();
    }

    private static IReadOnlyList<CommitTypeSchema> BuildAll() =>
    [
        // ── Combat ──────────────────────────────────────────────────────────────────
        new("hp", "Combat",
            "Adjust a character's HP by a delta. Positive heals, negative damages.",
            ["characterId", "delta"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"],
            Example: """{"$type":"hp","characterId":"chars/grog","delta":-8}"""),

        new("ruleset_action", "Combat",
            "ENGINE SIDE EFFECTS: Rolls dice and auto-applies HpChange, StatusChange, EngagementRelationChange. " +
            "Do NOT add separate hp/status commits for the same action — double-application will occur.",
            ["characterId", "actionName", "actionType", "actionCategory"],
            ["targetIds", "parameters", "advantageState", "damageType"],
            HasSideEffects: true,
            SideEffects: ["hp", "status", "engagement_relation"],
            CoCommitHints: ["event"],
            Example: """{"$type":"ruleset_action","characterId":"chars/asha","targetIds":["chars/bandit"],"actionName":"longsword","actionType":"Attack","actionCategory":"Melee"}"""),

        new("status", "Combat",
            "Add a structured status effect to a character (preferred: use 'effect' field for full control).",
            ["characterId"],
            ["effect", "status"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"],
            Example: """{"$type":"status","characterId":"chars/grog","effect":{"name":"Poisoned","category":"Poison","expiresAtRound":3}}"""),

        new("statusremove", "Combat",
            "Remove a named status condition from a character (case-insensitive, removes all matching).",
            ["characterId", "status"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: [],
            Example: """{"$type":"statusremove","characterId":"chars/grog","status":"Poisoned"}"""),

        new("level_up", "Combat",
            "Increase a character's level and apply ruleset-specific HP gains.",
            ["characterId"],
            ["levelsGained", "hpMode", "healToMatch", "classGained"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"]),

        new("rest", "Combat",
            "ENGINE SIDE EFFECTS: Calculates danger of the rest location and may emit encounter events. " +
            "Applies need recovery automatically. Resource pool recovery (spell slots/focus points) is deferred " +
            "to the next advance_world call — call advance_world after resting to refill pools.",
            ["characterId", "locationId", "intendedHours"],
            ["securityModifier", "narrativeNote"],
            HasSideEffects: true,
            SideEffects: ["need", "event"],
            CoCommitHints: ["event"],
            Example: """{"$type":"rest","characterId":"chars/valen","locationId":"locations/inn_room","intendedHours":8,"securityModifier":10}"""),

        new("scene_interrupt_check", "Combat",
            "ENGINE MACRO: Rolls crowd reaction and may emit an ActivityChange promoting a transient from the ambient crowd. " +
            "Cooldown: once per location per day. Call after tense beats in crowded locations only.",
            ["locationId", "characterId"],
            ["riskModifier", "notes"],
            HasSideEffects: true,
            SideEffects: ["activity"],
            CoCommitHints: [],
            Example: """{"$type":"scene_interrupt_check","locationId":"locations/market","characterId":"chars/valen","riskModifier":25}"""),

        // ── Narrative ────────────────────────────────────────────────────────────────
        new("event", "Narrative",
            "Record a noteworthy occurrence. Required after combat rounds, conversations, and discoveries to populate recall_history and get_npc_context.",
            ["summary"],
            ["category", "involved", "emotionalBeat", "relatedEntityId", "locationId", "relatedLocationIds", "eventId"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: [],
            Example: """{"$type":"event","summary":"Grog defeated the bandit captain","category":"Combat","involved":["chars/grog","chars/bandit-captain"]}"""),

        new("relationship", "Narrative",
            "Apply a numeric delta to one character's opinion of another. Include 'reason' for behavioral synthesis.",
            ["characterId", "targetId", "delta", "reason"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"]),

        new("mood", "Narrative",
            "Override a character's current mood string. Use for strong narrative moments.",
            ["characterId", "newMood"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("activity", "Narrative",
            "Update what an NPC is doing and/or where they are. Use liberally to keep get_scene in sync with narration.",
            ["characterId"],
            ["newActivity", "newLocationId", "updateLocation", "reason"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("need", "Narrative",
            "Adjust an NPC's named need (hunger, thirst, tiredness, etc.). Negative satisfies, positive increases.",
            ["characterId", "need", "delta"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("attribute", "Narrative",
            "Set or delta an arbitrary narrative attribute (willpower, morale, corruption, etc.). " +
            "'exhaustion_level' is the mechanical D&D 5e exhaustion track (1-6 scale) — distinct from " +
            "narrative tiredness, which is set via 'need' commits instead.",
            ["characterId", "attribute", "value"],
            ["isDelta"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("knowledge_update", "Narrative",
            "Store a memory in an NPC's psychology (topic, details, importance).",
            ["characterId", "topic", "details"],
            ["importance", "source", "valence", "salience", "urgency", "relatedEntityIds", "sourceEventIds"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("rumor_create", "Narrative",
            "Seed a new rumor. Starts at Nascent state.",
            ["rumorId", "subject", "text"],
            ["relatedLocationIds"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("rumor", "Narrative",
            "Advance or retire an existing rumor's lifecycle state.",
            ["rumorId", "newState"],
            ["newText"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        // ── World ────────────────────────────────────────────────────────────────────
        new("character_create", "World",
            "Create a new character. PCs should omit maxHp — bootstrap derives it from systemStats.",
            ["characterId", "name"],
            ["notes", "currentLocationId", "currentActivity", "keepAlive", "isPc", "isPartyCompanion",
             "schedule", "psychology", "maxHp", "currentHp", "systemStats", "classLevel"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("character_update", "World",
            "Patch visual appearance, tags, features, or party flags on an existing character.",
            ["characterId"],
            ["appearanceOverride", "tagsToAdd", "tagsToRemove", "featuresToAdd", "featuresToRemove",
             "keepAlive", "isPc", "isPartyCompanion", "systemStats"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("system_stats", "World",
            "Patch or bootstrap a character's ruleset-specific stats (partial merge).",
            ["characterId", "systemStats"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("location_create", "World",
            "Create a new location. Use connectedFromLocationId to auto-link with two-way exits.",
            ["locationId", "name", "description", "type"],
            ["parentLocationId", "connectedFromLocationId", "connectionDescription",
             "pointsOfInterest", "ambientCrowd", "exits", "dangerModifier"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("location_update", "World",
            "Granular updates to an existing location (exits, PoIs, tags, state).",
            ["locationId"],
            ["addExit", "removeExitTarget", "addPointOfInterest", "removePointOfInterest",
             "materializePointOfInterest", "poiDetails", "ambientCrowd", "name", "description",
             "newState", "tagsToAdd", "tagsToRemove", "featuresToAdd", "featuresToRemove", "dangerModifier"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("item_create", "World",
            "Create a new item in the world.",
            ["itemId", "name", "description", "holderId"],
            ["tags", "coreCategory", "properties", "quantity"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("item", "World",
            "Move an item to a new holder (character, location, or container item).",
            ["itemId", "toHolderId"],
            [],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("item_update", "World",
            "Update an item's state, category, tags, or properties.",
            ["itemId"],
            ["newState", "coreCategory", "tagsToAdd", "tagsToRemove", "featuresToAdd",
             "featuresToRemove", "propertiesToUpsert", "propertiesToRemove"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("travel", "World",
            "ENGINE SIDE EFFECTS: Auto-applies tiredness NeedChange, time advance, and optional random encounter.",
            ["characterId", "destinationLocationId"],
            ["narrative", "travelCostHoursOverride", "terrainOverride", "encounterRiskModifier"],
            HasSideEffects: true,
            SideEffects: ["need", "activity", "event"],
            CoCommitHints: ["event"],
            Example: """{"$type":"travel","characterId":"chars/valen","destinationLocationId":"locations/highpass","encounterRiskModifier":-10}"""),

        new("engagement_relation", "World",
            "Establish pairwise engagement state between two entities (grapple, embrace, watch). Bidirectional by default.",
            ["characterId", "targetId"],
            ["category", "verb", "restrictionLevel", "bidirectional"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("spatial_position", "World",
            "Set relative zone/distance positioning for a character.",
            ["characterId", "targetId"],
            ["distanceBand", "bearing", "zone"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("schedule_change", "World",
            "Change or remove a character's schedule (promotes transient → persistent or vice versa).",
            ["characterId"],
            ["schedule"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("faction_create", "World",
            "Create a new faction.",
            ["factionId", "name"],
            ["description", "factionType", "controllingTerritory", "territoryLocationIds",
             "knownLeaderIds", "initialInfluenceLevel"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: []),

        new("faction_reputation", "World",
            "Adjust a character's reputation with a faction.",
            ["characterId", "factionId", "delta"],
            ["reason"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"]),

        new("faction_state", "World",
            "Update a faction's stance toward another faction or its influence level.",
            ["factionId"],
            ["newStance", "targetFactionId", "influenceDelta", "narrative"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"]),

        new("quest_create", "World",
            "Create a new structured quest with objectives.",
            ["questId", "title"],
            ["giverId", "objectives", "category", "urgency", "relatedLocationIds",
             "relatedFactionIds", "dmNotes", "deadlineDay"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"]),

        new("quest_progress", "World",
            "Advance or fail a quest objective.",
            ["questId", "newState"],
            ["objectiveIndex", "objectiveName", "narrativeNote", "involvedIds"],
            HasSideEffects: false,
            SideEffects: ["event"],
            CoCommitHints: ["event"]),

        // ── PlotThread ───────────────────────────────────────────────────────────────
        new("plot_thread_create", "PlotThread",
            "Seed a DM-facing narrative arc. Unlike quests, plot threads tick forward invisibly. " +
            "Tension auto-escalates via simulation: Active→Escalating at 60, Escalating→Climax at 80.",
            ["plotThreadId", "title"],
            ["summary", "state", "tensionLevel", "clues", "involvedEntityIds", "resolutionCondition",
             "foreshadowingHooks", "dmNotes", "deadlineDay", "isPlayerVisible"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: [],
            Example: """{"$type":"plot_thread_create","plotThreadId":"plot-threads/guild-infiltration","title":"Guild Infiltration","summary":"Thieves guild is buying off city watch captains.","clues":[{"id":"clue-1","description":"Captain Maren's unusual wealth"}]}"""),

        new("plot_thread_progress", "PlotThread",
            "Update state, tension, notes, resolution condition, or involved entities of a plot thread.",
            ["plotThreadId"],
            ["newState", "tensionDelta", "resolutionCondition", "addForeshadowingHook",
             "addInvolvedEntityId", "removeInvolvedEntityId", "addClue", "narrativeNote"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event"],
            Example: """{"$type":"plot_thread_progress","plotThreadId":"plot-threads/guild-infiltration","tensionDelta":-20,"newState":"Resolved","narrativeNote":"Guild leader arrested."}"""),

        new("plot_thread_clue", "PlotThread",
            "Mark a clue as discovered. AUTO-EMITS an EventOccurred (Discovery) if narrativeNote is set. " +
            "Resets the staleness pressure timer.",
            ["plotThreadId", "clueId"],
            ["discoveredByCharacterIds", "narrativeNote"],
            HasSideEffects: true,
            SideEffects: ["event"],
            CoCommitHints: [],
            Example: """{"$type":"plot_thread_clue","plotThreadId":"plot-threads/guild-infiltration","clueId":"clue-1","discoveredByCharacterIds":["chars/valen"],"narrativeNote":"Found the captain's ledger."}"""),

        // ── Resources (Spells, Focus Points, Action Points) ────────────────────────────
        new("resource", "World",
            "Spend or recover a resource pool (spell slots, sorcerer points, focus points, action points). " +
            "Negative delta = spend (cast spell, use ability), positive = recover. Clamped to [0, max]. " +
            "Set spellName when spending spell_slots_* for slot-level validation (call get_spells for names).",
            ["characterId", "poolName", "delta"],
            ["reason", "spellName"],
            HasSideEffects: false,
            SideEffects: [],
            CoCommitHints: ["event", "status"],
            Example: """{"$type":"resource","characterId":"chars/wizard-1","poolName":"spell_slots_3","delta":-1,"spellName":"fireball","reason":"Cast Fireball"}"""),
    ];
}
