#!/usr/bin/env python3
"""Generate pf2e class progressions (and the creation fields of the class files) from Archives of Nethys
(Player Core, ORC-licensed).

For each class already in RulesetData/pf2e/classes/:
  - progressions/<class>.yaml is rebuilt from the class page's two tables: the class features per level (which feats
    and attribute boosts a level brings) and, for casters, the spells per day.
  - classes/<class>.yaml keeps its hand-kept fields (casterType, spellcastingAbility, pools, aliases) and gets its
    generated ones replaced: hitDie (the class's Hit Points per level) and skillChoices (the trained skills).

Requires network access to elasticsearch.aonprd.com.
"""

from __future__ import annotations

import html
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PF2E_DIR = ROOT / "src/CampaignVault/RulesetData/pf2e"
CLASSES_DIR = PF2E_DIR / "classes"
PROGRESSIONS_DIR = PF2E_DIR / "progressions"

HEADER = (
    "# Source: Pathfinder 2e Remastered (Player Core) by Paizo Inc., released under the Open RPG Creative (ORC)\n"
    "# License. Generated by scripts/generate_pf2e_classes.py from the Archives of Nethys database\n"
    "# (elasticsearch.aonprd.com); don't hand-edit.\n"
)
GENERATED_MARK = "# Generated by scripts/generate_pf2e_classes.py (below this line); the fields above are hand-kept."

# Classes are Player Core only: the classes/ folder holds the Player Core eight. See generate_pf2e_feats.py on scope.
AON_SEARCH_URL = "https://elasticsearch.aonprd.com/aon/_search"
AON_SOURCE = "Player Core"

SKILLS = [
    "Acrobatics", "Arcana", "Athletics", "Crafting", "Deception", "Diplomacy", "Intimidation", "Medicine",
    "Nature", "Occultism", "Performance", "Religion", "Society", "Stealth", "Survival", "Thievery",
]
ABILITIES = ["Strength", "Dexterity", "Constitution", "Intelligence", "Wisdom", "Charisma"]

# The level-1 class feature choices the builder asks for (class -> (choice key, AoN category, prompt, the class
# features table's name for it)). Each option is an AoN entry of that category; its text says which skills it trains
# ("You're trained in Thievery", "Patron Skill Religion") and whether it changes the key attribute. A cleric's deity
# isn't here: deities are setting content (LICENSING.md), so "a skill determined by your deity" stays a free pick.
CLASS_CHOICES = {
    "bard": [("muse", "muse", "Muse", "muse")],
    "cleric": [("doctrine", "doctrine", "Doctrine", "doctrine")],
    "druid": [("order", "druidic-order", "Druidic order", "druidic order")],
    "ranger": [("huntersEdge", "hunters-edge", "Hunter's edge", "hunter’s edge")],
    "rogue": [("racket", "racket", "Rogue's racket", "rogue’s racket")],
    "witch": [("patron", "patron", "Patron", "patron")],
    "wizard": [("school", "arcane-school", "Arcane school", "arcane school"), ("thesis", "arcane-thesis", "Arcane thesis", "arcane thesis")],
}

# Player Core's druidic order entries on AoN don't state the order's skill (the book's order sidebar does), so it is
# kept here. The generator stops if an order is missing, so a new order can't come through without one.
ORDER_SKILLS = {"Animal": "Athletics", "Leaf": "Diplomacy", "Storm": "Acrobatics", "Untamed": "Intimidation"}

# Setting names an option's opening could carry (LICENSING.md keeps setting content out): a sentence with one is
# skipped for the next.
SETTING_NAMES = ["Golarion", "Absalom", "Magnimar", "Abadar", "Gorum", "Manaket", "Occularium", "Iomedae", "Pharasma"]

# What a caster picks at creation (the builder's cantrips and spells), per Player Core:
#   spellbook: a wizard's spellbook, a witch's familiar: 10 cantrips and five 1st-rank spells, two more spells a level.
#   repertoire: a spontaneous caster's repertoire, which is the size of the spells-per-day table.
#   prepared: a prepared caster with no book (cleric, druid) prepares from the whole list; the picks are what's
#     prepared, so the spells-per-day table.
SPELL_PICKS = {"wizard": "spellbook", "witch": "spellbook", "bard": "repertoire", "cleric": "prepared", "druid": "prepared"}


def fetch_json(url: str, data: bytes) -> dict:
    req = urllib.request.Request(
        url, headers={"User-Agent": "CampaignVault/1.0", "Content-Type": "application/json"}, data=data
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def fetch_class(name: str) -> dict:
    query = {
        "size": 1,
        "query": {
            "bool": {
                "must": [
                    {"term": {"category": "class"}},
                    {"term": {"name.keyword": name}},
                    {"term": {"primary_source.keyword": AON_SOURCE}},
                ]
            }
        },
    }
    hits = fetch_json(AON_SEARCH_URL, json.dumps(query).encode("utf-8"))["hits"]["hits"]
    if not hits:
        raise SystemExit(f"No {AON_SOURCE} class named {name} on Archives of Nethys.")
    return hits[0]["_source"]


def fetch_category(category: str) -> list[dict]:
    query = {
        "size": 100,
        "query": {"bool": {"must": [{"term": {"category": category}}, {"term": {"primary_source.keyword": AON_SOURCE}}]}},
        "sort": [{"name.keyword": "asc"}],
    }
    hits = fetch_json(AON_SEARCH_URL, json.dumps(query).encode("utf-8"))["hits"]["hits"]
    docs = [h["_source"] for h in hits if (h["_source"].get("rarity") or "common") == "common"]
    if not docs:
        raise SystemExit(f"No {AON_SOURCE} entries in the AoN category {category}.")
    return docs


def option_text(doc: dict) -> str:
    """The entry's text after its "Source Player Core pg. N" line."""
    text = re.sub(r"\s+", " ", doc.get("text") or "").strip()
    text = re.sub(r"^.*?Source [^.]*? pg\. \d+\s*", "", text, count=1)
    # A Pathfinder Society ruling AoN puts first isn't part of the entry.
    return re.sub(r"^PFS Note .*?[.!?]\s+", "", text, count=1)


def option_skills(doc: dict, category: str) -> tuple[list[str], int]:
    """The skills an option trains, and how many more it lets the character pick (the mastermind's "one of the following")."""
    if category == "druidic-order":
        if doc["name"] not in ORDER_SKILLS:
            raise SystemExit(f"No skill for the druidic order {doc['name']}: add it to ORDER_SKILLS.")
        return [ORDER_SKILLS[doc["name"]]], 0
    text = option_text(doc)
    skills: list[str] = []
    for m in re.finditer(r"(?:You are|You['’]re) trained in ([A-Z]\w+)(?: and ([A-Z]\w+))?", text):
        skills += [g for g in m.groups() if g]
    if m := re.search(r"Patron Skill ([A-Z]\w+)", text):
        skills.append(m.group(1))
    unknown = [k for k in skills if k not in SKILLS]
    if unknown:
        raise SystemExit(f"{doc['name']}: unknown skills {unknown}.")
    extra = 1 if re.search(r"one of the following skills of your choice", text) else 0
    return skills, extra


def option_key_ability(doc: dict) -> str | None:
    m = re.search(r"You can choose (\w+) as your key attribute", option_text(doc))
    if m and m.group(1) not in ABILITIES:
        raise SystemExit(f"{doc['name']}: unknown key attribute {m.group(1)}.")
    return m.group(1) if m else None


def option_description(doc: dict, skills: list[str], extra: int, key: str | None) -> str:
    """The entry's first sentence that names no setting place or god, then what it gives the builder: its skills and key attribute."""
    sentences = [t.strip() for t in re.split(r"(?<=[.!?])\s", option_text(doc)) if t.strip()]
    first = next((t for t in sentences[:3] if not any(n in t for n in SETTING_NAMES)), None)
    if first is None:
        raise SystemExit(f"{doc['name']}: its opening sentences name setting content (LICENSING.md).")
    parts = [first]
    if skills:
        parts.append(f"Trained in {' and '.join(skills)}" + (" and one more skill." if extra else "."))
    if key:
        parts.append(f"{key} can be your key attribute.")
    return " ".join(parts)


def class_choices(class_name: str) -> list[str]:
    """The level-1 feature entries (YAML lines under features:) with their choices."""
    lines = []
    for key, category, prompt, _ in CLASS_CHOICES.get(class_name, []):
        lines.append(f"      - name: {json.dumps(prompt)}")
        lines.append("        choices:")
        lines.append(f"          {key}:")
        lines.append("            type: Enum")
        lines.append("            required: true")
        lines.append("            options:")
        for doc in fetch_category(category):
            skills, extra = option_skills(doc, category)
            key_ability = option_key_ability(doc)
            lines.append(f"              - id: {slug(doc['name'])}")
            lines.append(f"                label: {json.dumps(doc['name'], ensure_ascii=False)}")
            lines.append(f"                description: {json.dumps(option_description(doc, skills, extra, key_ability), ensure_ascii=False)}")
            if skills:
                lines.append(f"                skills: {flow(skills)}")
            if extra:
                lines.append(f"                extraSkills: {extra}")
            if key_ability:
                lines.append(f"                keyAbility: {key_ability}")
    return lines


# House rule (RULES_GAPS.md): Pathfinder has a cleric always follow a deity, whose domains and font they get. The shipped
# data has no deities (setting content, LICENSING.md), so a cleric picks two domains and the divine font directly. A deity
# plugin's named power (`powers/`, `offers:` for domains, `narrows:` for the font) then narrows these choices to the
# deity's. Only the domain *names* are read from AoN; their text lists deities.
HOUSE_CHOICES = {"cleric": "Divine calling"}
HOUSE_FONTS = [
    ("healingFont", "Healing font", "You can cast the heal spell extra times each day, restoring hit points to the living."),
    ("harmfulFont", "Harmful font", "You can cast the harm spell extra times each day, wounding the living and healing the undead."),
]


def house_choices(class_name: str) -> list[str]:
    """The level-1 feature (YAML lines under features:) for the no-deity house rule, or none for a class without one."""
    if class_name not in HOUSE_CHOICES:
        return []
    lines = [f"      - name: {json.dumps(HOUSE_CHOICES[class_name])}", "        choices:", "          domain:",
             "            type: Enum", "            required: true", "            count: 2", "            options:"]
    for doc in fetch_category("domain"):
        lines.append(f"              - id: {slug(doc['name'])}")
        lines.append(f"                label: {json.dumps(doc['name'], ensure_ascii=False)}")
        lines.append(f"                description: {json.dumps('A divine domain: its focus spells and its place in your faith.')}")
    lines += ["          font:", "            type: Enum", "            required: true", "            options:"]
    for key, label, text in HOUSE_FONTS:
        lines += [f"              - id: {key}", f"                label: {json.dumps(label)}", f"                description: {json.dumps(text)}"]
    return lines


def slug(name: str) -> str:
    """"School of Battle Magic" -> "schoolOfBattleMagic", "Faith's Flamekeeper" -> "faithsFlamekeeper"."""
    words = re.sub(r"[^A-Za-z0-9 ]", "", name).split()
    return words[0].lower() + "".join(w[:1].upper() + w[1:] for w in words[1:])


# Choices every level brings by the class features table (beyond level 1, whose boosts are the recipe's allocate steps):
# a skill increase is one skill a rank up; attribute boosts are four different attributes, each +1.
LEVEL_CHOICES = {
    "skill increase": ("Skill increase", "skillIncrease", "SkillIncrease", None),
    "attribute boosts": ("Attribute boosts", "attributeBoosts", "AttributeBoosts", 4),
}


def tables(markdown: str) -> list[list[list[str]]]:
    """Every <table> in the page as rows of cell texts (the header row included)."""
    result = []
    for table in re.findall(r"<table>(.*?)</table>", markdown, re.S):
        rows = []
        for row in re.findall(r"<tr>(.*?)</tr>", table, re.S):
            cells = re.findall(r"<t[hd][^>]*>(.*?)</t[hd]>", row, re.S)
            rows.append([html.unescape(re.sub(r"<[^>]+>", "", c)).strip() for c in cells])
        result.append(rows)
    return result


def feature_table(markdown: str) -> dict[int, list[str]]:
    for rows in tables(markdown):
        if rows and rows[0][:2] == ["Your Level", "Class Features"]:
            return {int(r[0]): [f.strip() for f in r[1].split(",") if f.strip()] for r in rows[1:] if r[0].isdigit()}
    raise SystemExit("No class features table.")


def slot_table(markdown: str) -> dict[int, list[int]]:
    """Level → [cantrips, 1st, 2nd, ...] from the spells-per-day table, or {} for a class without one."""
    for rows in tables(markdown):
        if rows and rows[0][:2] == ["Your Level", "Cantrips"]:
            # Footnote rows ("* The magnum opus ...") and marks on a count ("1*") are not part of the counts.
            return {int(r[0]): [int(re.sub(r"\D", "", c) or 0) for c in r[1:]] for r in rows[1:] if r[0].isdigit()}
    return {}


def level_counts(class_name: str, level: int, features: list[str]) -> dict[str, int]:
    lower = [f.lower() for f in features]
    counts = {
        "classFeats": sum(1 for f in lower if f == f"{class_name} feat"),
        "skillFeats": sum(1 for f in lower if f == "skill feat"),
        "generalFeats": sum(1 for f in lower if f == "general feat"),
        "ancestryFeats": sum(1 for f in lower if f == "ancestry feat"),
        "abilityBoosts": 4 if "attribute boosts" in lower else 0,
    }
    # Level 1's "Ancestry and background" brings the first ancestry feat.
    if level == 1 and "ancestry and background" in lower:
        counts["ancestryFeats"] += 1
    return counts


def spell_counts(class_name: str, level: int, slots: dict[int, list[int]]) -> tuple[int, int] | None:
    kind = SPELL_PICKS.get(class_name)
    if kind is None or level not in slots:
        return None
    row = slots[level]
    if kind == "spellbook":
        return 10, 5 + 2 * (level - 1)
    return row[0], sum(row[1:])


def skill_choices(class_doc: dict) -> dict:
    """Player Core's trained-skills lines → trained (fixed), oneOf (pick one of these), count (more, of any skill).

    "One skill determined by your deity / order / racket / patron" depends on a class feature the builder doesn't
    ask for yet, so it is one more free pick.
    """
    trained, one_of, count = [], [], 0
    for line in class_doc.get("skill_proficiency") or []:
        text = line.strip().rstrip(".")
        if m := re.search(r"additional skills equal to (\d+) plus", text):
            count += int(m.group(1))
        elif m := re.search(r"skills equal to (\d+) plus", text):
            count += int(m.group(1))
        elif m := re.fullmatch(r"Trained in your choice of (\w+) or (\w+)", text):
            one_of = [m.group(1), m.group(2)]
            count += 1
        elif "determined by" in text:
            # The racket, order or patron now says which (its option's skills); a deity is still a free pick.
            if not any(k in text for k in ("racket", "druidic order", "patron")):
                count += 2 if text.startswith("Trained in two") else 1
        elif m := re.fullmatch(r"Trained in (\w+)", text):
            if m.group(1) not in SKILLS:
                raise SystemExit(f"{class_doc['name']}: unknown skill in '{line}'.")
            trained.append(m.group(1))
        else:
            raise SystemExit(f"{class_doc['name']}: can't read the skill line '{line}'.")
    return {"trained": trained, "oneOf": one_of, "count": count}


def key_abilities(class_doc: dict) -> list[str]:
    attrs = class_doc.get("attribute") or []
    if "other" in attrs:
        # The rogue's racket can make its key attribute Strength, Intelligence or Charisma instead of Dexterity: the
        # racket options carry that (keyAbility), so the class lists only its own.
        return [a for a in ABILITIES if a in attrs]
    unknown = [a for a in attrs if a not in ABILITIES]
    if unknown:
        raise SystemExit(f"{class_doc['name']}: unknown key attributes {unknown}.")
    return attrs


def flow(values: list[str]) -> str:
    return "[" + ", ".join(values) + "]"


def write_progression(class_name: str, class_doc: dict) -> None:
    features = feature_table(class_doc["markdown"])
    slots = slot_table(class_doc["markdown"])
    lines = [HEADER.rstrip()]
    lines.append(f"name: {class_name}")
    lines.append("system: pf2e")
    lines.append(f"className: {class_doc['name']}")
    lines.append(f"hitDie: d{class_doc['hp']}")
    lines.append(f"aliases: [{class_name}]")
    lines.append(f"keyAbility: {flow(key_abilities(class_doc))}")
    lines.append("levels:")
    for level in sorted(features):
        lines.append(f"  {level}:")
        # A feature that asks for a choice is a mapping with its choices (the rest stay plain names).
        names, chosen = [], []
        for f in features[level]:
            lower = f.lower()
            if level > 1 and lower in LEVEL_CHOICES:
                prompt, key, kind, count = LEVEL_CHOICES[lower]
                chosen += [f"      - name: {prompt}", "        choices:", f"          {key}:", f"            type: {kind}", "            required: true"]
                if count:
                    chosen.append(f"            count: {count}")
            elif level == 1 and any(lower == c[3] for c in CLASS_CHOICES.get(class_name, [])):
                continue
            else:
                names.append(f)
        if level == 1:
            chosen += class_choices(class_name) + house_choices(class_name)
        quoted = [json.dumps(f) if re.search(r"[:,\[\]{}#&*!|>'\"%@`’]", f) else f for f in names]
        if chosen:
            lines.append("    features:")
            lines += [f"      - {q}" for q in quoted]
            lines += chosen
        else:
            lines.append("    features: " + flow(quoted))
        for key, value in level_counts(class_name, level, features[level]).items():
            if value:
                lines.append(f"    {key}: {value}")
        if (spells := spell_counts(class_name, level, slots)) is not None:
            lines.append(f"    cantripsKnown: {spells[0]}")
            lines.append(f"    spellsKnown: {spells[1]}")
    (PROGRESSIONS_DIR / f"{class_name}.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def update_class(path: Path, class_doc: dict) -> None:
    """Keeps the hand-kept fields, drops the old generated ones (and anything after the mark), appends the new."""
    managed = ("hitDie:", "skillChoices:")
    kept, skipping = [], False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line == GENERATED_MARK:
            break
        if line.startswith(managed):
            skipping = True
            continue
        if skipping and line.startswith((" ", "\t")):
            continue
        skipping = False
        kept.append(line)
    while kept and not kept[-1].strip():
        kept.pop()

    choices = skill_choices(class_doc)
    generated = [GENERATED_MARK, f"hitDie: d{class_doc['hp']}", "skillChoices:", f"  count: {choices['count']}", "  from: [any]"]
    if choices["trained"]:
        generated.append(f"  trained: {flow(choices['trained'])}")
    if choices["oneOf"]:
        generated.append(f"  oneOf: {flow(choices['oneOf'])}")
    path.write_text("\n".join(kept + generated) + "\n", encoding="utf-8")


def generate() -> int:
    print(f"  pf2e classes source: {AON_SEARCH_URL} (Archives of Nethys, {AON_SOURCE})")
    classes = sorted(p.stem for p in CLASSES_DIR.glob("*.yaml"))
    PROGRESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    for class_name in classes:
        doc = fetch_class(class_name.capitalize())
        write_progression(class_name, doc)
        update_class(CLASSES_DIR / f"{class_name}.yaml", doc)
    print(f"Generated {len(classes)} pf2e progressions and class creation fields: {', '.join(classes)}")
    return len(classes)


if __name__ == "__main__":
    generate()
